apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "simplenodeservice-team42-preprod"
  title: "simplenodeservice-team42-preprod"
  description: "Template for the simplenodeservice owned and operated by team42 in environment preprod"
  annotations:
    backstage.io/techdocs-ref: dir:.
    # Not working
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=userinterface'
    'backstage.io/kubernetes-namespace': 'simplenodeservice-team42-preprod'
    argocd/app-name: simplenodeservice-team42-preprod
  links:
    - url: https://github.com/fr3ddykrueger/platform-engineering-demo.git
      title: Github Repo
      icon: github
    - url: https://animated-robot-9w9vp5qpr9qfxgqp-80.app.github.dev/simplenodeservice-team42-preprod
      title: "Browse Application"
      icon: subject
    - title: View in ArgoCD
      icon: catalog
      url: https://animated-robot-9w9vp5qpr9qfxgqp-30100.app.github.dev/applications/argocd/simplenodeservice-team42-preprod
    - title: View in Dynatrace
      icon: catalog
      url: https://ryo61641.apps.dynatrace.com
    - url: https://community.dynatrace.com
      title: Dynatrace community
      icon: dashboard
spec:
  type: website
  owner: team42
  lifecycle: preprod
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "team42"
  description: Group for application team team42
spec:
  type: business-unit
  profile:
    displayName: Test-Team 01
    email: testteam01@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  parent: applications
  children: []
#   members: [jdoe]
